name: Release Windows
on: workflow_dispatch

jobs:
  release-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15
          tools: 'tools_ifw'
          add-tools-to-path: true
          cache: true

      - name: Make release
        id: run-windows-build
        run: |
          mkdir build; cd build
          cmake -DCMAKE_BUILD_TYPE=Release ./..
          cmake --build . --target PACKAGE --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: skvm-windows.exe
          path: install/pack/SKVM*.exe
