name: Release Linux
on: workflow_dispatch

jobs:
  release-linux:
    runs-on: ubuntu-latest
    container: sgad/skvm:ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build deb
        id: run-build
        run: |
          mkdir deb; cd deb
          cmake -DCMAKE_BUILD_TYPE=Release -DSKVM_PACKAGE_TYPE=deb ./..
          make package

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          path: deb/SKVM*.deb

      - name: Build rpm
        id: run-build
        run: |
          cd ..; mkdir rpm; cd rpm
          cmake -DCMAKE_BUILD_TYPE=Release -DSKVM_PACKAGE_TYPE=rpm ./..
          make package

      - name: Upload rpm
        uses: actions/upload-artifact@v3
        with:
          path: rpm/SKVM*.rpm
