name: Release macOS
on: workflow_dispatch

jobs:
  release-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install the Apple certificate
        env:
          MAC_CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
          MAC_CERT_PASSWORD: ${{ secrets.MAC_CERT_PASSWORD }}
          KEYCHAIN_PASSWORD: "password"
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$MAC_CERTIFICATE" | base64 --decode -o $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$MAC_CERT_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Install QT
        run: brew install qt@5

      - name: Make release
        id: run-macos-build
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_INSTALL_PREFIX="./../install" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$(brew --prefix qt5)" ./..

          make -j package

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: skvm-macos.dmg
          path: install/pack/SKVM*.dmg
